### ISSUE TITLE
LocalStorage has limits of 5mb

### ISSUE THREAD

**Issue by Digity101** [mtkwock/Valeria#11]
DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'dataSourceCachePlayerSkill' exceeded the quota

**Comment by mtkwock** [comment]
I've updated the localStorage caching of Ilmina's data along with team data to use the LZUTF8 compression implementation.  This decreases the usage to ~2MB which should give plenty of room to grow.  (Notably, the errors don't show up anymore.)
