### ISSUE TITLE
Damage calculation appears to be incorrect

### ISSUE THREAD

**Issue by weschao** [mtkwock/Valeria#32]
https://mtkwock.github.io/Valeria/?team=AQLfqBxjhumZWcqR44Z5kdwKn+OSSW6ZriybVjhkmZnEqSY4bpmtpKk+OGOYA&dungeon=2660002

Enemy: F23 Borma
Combo: rgbllduuu Bl

This reports that Yuna does 53m damage and 47m effective damage, but Borma has a 15m damage void and Yuna doesn't have a VDP awakening, so I don't think that's possible.

**Comment by mtkwock** [comment]
Figured out the error.  I'd not added the check for having vdp awakenings as a requirement for ignoreVoid to be true.  This has been updated.
