### ISSUE TITLE
Make teams/builds sharable with a link

### ISSUE THREAD

**Issue by Digity101** [mtkwock/Valeria#5]
Some ideas to do this are to export the team/build to json with unique id, store the json in a database and then retrieve the json if the link has some parameters. Other approach is to serialize the json file into a string and include it as link parameter

**Comment by weschao** [comment]
It looks like this got implemented already -- the Get Link button under Monster Editor retrieves a link for the team and dungeon.

**Comment by weschao** [comment]
Confirm that this works across servers; I can copy the link on github.io, replace the URL with localhost:4800, and retrieve the team.
